### ISSUE TITLE
contract state with iface fungible strange

### ISSUE THREAD

**Issue by Matrix-Zhang** [RGB-WG/rgb-std#186] opened 2024-04-10 12:12 UTC
when we get contract state with iface.fungible(), it return wrong assertOwner

the asset was issued at seal: a0ea0a6b4f9e52d2b12a1f7872c66f6576edfe5b2d88ad158f1d33835068a040:1

then we transfer someone others, the new seal is 41563b544dc1018162fae1e63c471a0693514aeeda4bc96307f5bdcb5933f97f:0

but when we fetch the contract state with iface.fungible(), it just rerturn a0ea0a6b4f9e52d2b12a1f7872c66f6576edfe5b2d88ad158f1d33835068a040:1

the attachment is the stock.dat

i peek it with hex editor, i can found 41563b544dc1018162fae1e63c471a0693514aeeda4bc96307f5bdcb5933f97f

[stock.dat.zip](https://github.com/RGB-WG/rgb-std/files/14931935/stock.dat.zip)

**Comment by dr-orlovsky** [comment] 2024-04-10 12:49
Do you use v0.11.0-beta.5 from crates.io?

**Comment by Matrix-Zhang** [comment] 2024-04-11 02:19
> Do you use v0.11.0-beta.5 from crates.io?

yes, the version is beta.5

**Comment by dr-orlovsky** [comment] 2024-04-11 06:18
> but when we fetch the contract state with iface.fungible(), it just rerturn 

on sender or receiver? 

The attached stock is whose?

**Comment by dr-orlovsky** [comment] 2024-06-08 16:00
I am pretty sure the issue is closed in one of PRs we had in may. Can you pls check that now the system works correctly?

**Closed** 2024-07-11 09:04 UTC
