### ISSUE TITLE
recipient fails to accept a transfer spending a blank allocation

### ISSUE THREAD

**Issue by nicbus** [RGB-WG/rgb-std#195] opened 2024-04-18 15:48 UTC
Using commit `f9813b7` plus a cargo update to include rgb-std #193 I face an issue.

This is what I'm doing (wallet 1 is the issuer/sender, wallet 2 is the recipient):
- issue a NIA asset on wallet 1
- issue a CFA asset on wallet 1
- send some NIA assets from wallet 1 to wallet 2
- send some CFA assets (spending blank allocation) from wallet 1 to wallet 2

The 2nd transfer fails when the recipient tries to accept it with the following error:
```
Error: anchors for the same witness do not match each other.
```

**Comment by dr-orlovsky** [comment] 2024-04-18 17:01
I need the second consignment and the data directories from both sender and receiver

**Comment by dr-orlovsky** [comment] 2024-04-18 17:09
Ok, I found a problem, here the data are not needed. The problem is related to comparison code for two anchors when they provide different proofs for different contracts

**Comment by dr-orlovsky** [comment] 2024-04-18 17:56
The solution is three-part one (all are `v0.11` branches, so just do `cargo update`). Basically, instead of comparing anchors I had to do a dedicated operation which takes into an account that equivalent anchors may still have different parts concealed.

- https://github.com/RGB-WG/rgb-std/commit/f11cd3930bc8e5d19a509553968459e32e4927ee
- https://github.com/LNP-BP/client_side_validation/pull/165
- https://github.com/BP-WG/bp-core/pull/86

**Comment by dr-orlovsky** [comment] 2024-04-19 07:45
Sorry, I mistakenly merged PR and it closed this issue. Feel free to re-open it if the PR hasn't fixed it.

**Closed** 2024-04-19 07:45 UTC
Labels: bug
